canonical/jepsen.dqlite

.github/workflows/test.yml

Work around for https://github.com/actions/upload-artifact/issues/92

actions: Artifact upload doesn't support symbolic link to directory

---

.github/workflows/test.yml
project.clj
resources/bridge.sh
src/jepsen/dqlite/control.clj
src/jepsen/dqlite/db.clj
src/jepsen/os/container.clj

- Update Jepsen to 0.2.4 in order to use the new `env` option of `start-daemon!` so that the tracing environment variables are picked up correctly by the dqlite application.
- Build raft & dqlite from source so we're sure it's always latest, greatest.
- The time nemesis that is run by default in 0.2.4 uses `ntpdate`, I had to adapt some networking related settings so that the containers used in the test can perform dns lookups to find the ntp servers. The way I did it might be a bit hacky.

Upgrade to Jepsen 0.2.4 to enable tracing.

---

src/jepsen/os/container.clj

The let binding is not really necessary, but I think it's more readable instead of just prepending the ps command with a sleep. Should eliminate some false failures.

container: Sleep before `ps` to determine pid.

---

resources/app.go

It means that another transaction is already busy setting up the data
for the test and we can safely back off.
Should eliminate some setup failures in the jepsen bank suite.

app: Don't return err when ErrBusySnapshot

---

.github/workflows/test.yml

nemesis don't look stable for long running tests

runner: decrease runtime

---

src/jepsen/dqlite/db.clj

Otherwise start-stop-daemon can start complaining and the node won't be
able to be restarted after stopping it.

db: Remove pidfile when stopping node

---

resources/app.go

This will hopefully increase the odds of finding a corrupt
segment at startup after killing/stopping node while still being
representative for the default settings in raft. Current test settings
were triggering snapshots a bit too frequently and didn't leave enough
closed segments around.

app: Tweak snapshot parameters

---

src/jepsen/dqlite/db.clj

2022-09-21 22:06:19,003{GMT}    WARN    [jepsen worker nemesis] jepsen.generator.interpreter: Process :nemesis crashed
clojure.lang.ExceptionInfo: Command exited with non-zero status 1 on node n1:
cd /; rm -rf /opt/dqlite/data/* /opt/dqlite/data/.*
STDIN:
null
STDOUT:
STDERR:
rm: refusing to remove '.' or '..' directory: skipping '/opt/dqlite/data/.'
rm: refusing to remove '.' or '..' directory: skipping '/opt/dqlite/data/..'

db: Prevent wipe function from crashing nemesis.

---

.github/workflows/test.yml
src/jepsen/dqlite.clj
src/jepsen/dqlite/control.clj
src/jepsen/dqlite/db.clj

Our homegrown assertion and core dump checkers were previously trying to access the log and core dump files on the (simulated) remote nodes after those nodes had been torn down, which can't work. The resulting errors were masked by a catch block around the corresponding `jepsen.control/exec` call. I've replaced the assertion checker with `jepsen.checker/log-file-pattern`, which implements just the logic we want; and the core dump checker is rewritten to look for dump files after they've been copied over from the remote nodes.
Signed-off-by: Cole Miller <cole.miller@canonical.com>

Fix the assertion and core dump checkers

---

src/jepsen/dqlite/db.clj

Signed-off-by: Cole Miller <cole.miller@canonical.com>

Save the app binary when a core dump occurs

---

.github/workflows/test.yml

12am, 6am, 12pm, 6pm
Tests fail to often to run hourly now.

actions: Run every 6th hour

---

.github/workflows/test.yml

This will at least fail the jobs instead of letting them sit around for hours. Still debugging cause of hang.

actions: Add timeouts to Job and Test Step.

---

.github/workflows/test.yml

This is an attempt to prevent `ntpdate[314]: no server suitable for synchronization found` that is sometimes observed in the tests.

.github: stop systemd.timesyncd

---

.github/workflows/test.yml
resources/network.sh
src/jepsen/dqlite/nemesis.clj
src/jepsen/os/container.clj

It seems that #62 made Jepsen less effective at finding crashes in raft/dqlite -- which is unexpected, since the clock nemesis shouldn't even work inside `nsenter`! Let's restore it until we figure out what's going on.
This reverts commit 281f8b4d65e16c2d6357edaf438c116c8794cb3c.
Signed-off-by: Cole Miller <cole.miller@canonical.com>

Put the clock nemesis back

---

src/jepsen/dqlite.clj

This should e.g. allow nodes that were asked to stop just before healing the cluster to stop properly.
(should) fix #74

dqlite: Sleep before healing cluster

---

.github/workflows/test.yml

Hi,
This PR adds the ability to manually trigger test runs with arbitrary test/raft/dqlite repositories/branches.
No more submitting fake PRs to trigger a test run!
It adds an `on workflow_dispatch` to the action.
This will add a `Run Workflow` button to Actions -> Dqlite Jepsen tests:

GitHub action: enable manually triggering test runs with arbitrary test/raft/dqlite repositories/branches

---

.github/workflows/test.yml
go.mod
go.sum

GitHub has been exhibiting high latency/failures retrieving from repositories.
This PR reduces the false positive, failing due to GitHub, test failures.
Make the action more efficient  by  caching:
- Go modules
- Jepsen dependencies
Tune the timeout budget:
- increase total job timeout
- add specific timeout for setup step
(Some jobs were just barely timing out in the actual test step as setup had used most of the total.)

Github action latency/timeouts/failures: cache Go mods and Jepsen deps, tune job/step timeouts

---

src/jepsen/dqlite.clj
src/jepsen/dqlite/append.clj
src/jepsen/dqlite/bank.clj

This PR tunes the list-append test opts:
```clj
{:key-count           12 ;; prev 10
:min-txn-length       1 ;; same
:max-txn-length       4 ;; prev 2
:max-writes-per-key 128 ;; prev 32
}
```
Increasing the number of active keys, operations per transaction, and the active lifetime of a key will:
- drive dqlite with a more complex workload
- provide Jepsen a richer log file to analyze for consistency
- increase confidence in the results
The new values are consistent with the latest Jepsen RedisRaft and MongoDB tests.
----
Handle workloads consistently when building test map.
By convention:
```clj
(merge tests/noop-test
cli-ops
workload-results
{:test-and-business :logic-config})
```

Tune list-append test, and uniform handling of workloads

---

.github/workflows/test.yml
.gitignore
project.clj

- Make the workflow callable from other workflows:
- other repositories can call the workflow `with:` different `inputs:` for testing
- specify a branch upgraded to the latest Jepsen
- locally install/build an arbitrary Jepsen
- same with raft/dqlite
- Better artifacts
- Summary for quick click and scan of results, latency plot, tail of log
- Avoid duplicate files, symlinks, in failure artifact 
- Try and fix occasional test failures cased by a race between the `ufw` calls, `sleep 0.200`
- Enable building docs
- Common Clojure `.gitignore`
----
I think this is the smallest YAML possible.
GitHub doesn't support:
- YAML anchors/aliases, &/*, for repeated text
- `env.` values in the `inputs:` context
So some repetition.
----
A workflow that shadows jepsen.dqlite tests but with latest Jepsen: …

More testable workflow: make callable, better artifacts

---

project.clj

This PR is a followup of #87 that updates Jepsen to the latest version.
In the original PR, @MathieuBordere asked to [test the tests](https://github.com/canonical/jepsen.dqlite/pull/87#issuecomment-1467755261).
Since that time, a shadow repository has been running the tests with a branch updated to Jepsen 0.3.2-SNAPSHOT:
```yaml
name: Test dqlite.jepsen
on:
schedule:
- cron: "0/30 * * * *"
jobs:
call-jepsen-dqlite:
uses: nurturenature/jepsen.dqlite/.github/workflows/test.yml@latest-jepsen
with:
jepsenDqliteRepo: nurturenature/jepsen.dqlite
jepsenDqliteBranch: latest-jepsen
```
and the test [pass/fail results](https://github.com/nurturenature/jepsen.dqlite-test/actions) have been comparable.

Update Jepsen to 0.3.2-SNAPSHOT

---

.github/workflows/test-build-run.yml
.github/workflows/test-custom.yml
.github/workflows/test-fail.yml
.github/workflows/test.yml

Move the disk tests to the expect fail suite as there are a couple of them that consistently fail.

workflows: Move disk tests to expect fail.

---

src/jepsen/dqlite.clj

The new pattern allows to catch errors propagated from failing to start the raft node while not matching normal log lines.
example error that is still caught
>raft_start(): io: closed segment 0000xxxx-0000xxxx is past last snapshot-x-xxxx-xxxxxx
quick fix for #136 , should probably take a deeper look at it, but I want the jepsen tests to run.

dqlite: Don't trigger assertion pattern on non-error log.
